// export const FETCHING_ARTICLES = "FETCHING_ARTICLES";
// export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
// export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";

const ACTION_TYPES = {
  API_PENDING: "API_PENDING",
  API_SUCCESS: "API_SUCCESS",
  API_FAILURE: "API_FAILURE",
};

export default ACTION_TYPES;
